# Fabric notebook source

# METADATA ********************

# META {
# META   "kernel_info": {
# META     "name": "synapse_pyspark"
# META   },
# META   "dependencies": {
# META     "lakehouse": {
# META       "default_lakehouse": "7f45a2ed-125b-448d-bf75-2a9613526182",
# META       "default_lakehouse_name": "capacity_metrics",
# META       "default_lakehouse_workspace_id": "cb2325c3-50bc-40bf-91c8-49effb0200d8",
# META       "known_lakehouses": [
# META         {
# META           "id": "7f45a2ed-125b-448d-bf75-2a9613526182"
# META         }
# META       ]
# META     },
# META     "warehouse": {
# META       "known_warehouses": []
# META     }
# META   }
# META }

# MARKDOWN ********************

# # nb_0220_collect_timepoint_detail
# 
# ## Purpose
# Collect per-timepoint **detail** records for **standard capacity** operations from the
# Fabric Capacity Metrics semantic model. Each timepoint result is first staged into a
# temporary persisted **non-Spark** structure under `Files/tmp`, then the notebook performs
# a single final upsert (MERGE) into `silver.timepoint_metrics` so re-runs stay idempotent
# while avoiding per-timepoint MERGE overhead.
# 
# ## Inputs
# - `nb_0110_shared_config` — all config
# - `gold.capacity_calendar_timepoints` — calendar of valid timepoints (prerequisite)
# 
# ## Outputs
# - `silver.timepoint_metrics` — per-timepoint activity records, MERGED once per notebook run on CapacityId + TimePoint + Unique_key + Operation + Operation_Id + Operation_start_time + Operation_end_time
# 
# ## Execution Order
# 1. Run `nb_0210_collect_capacity_metrics` first (to populate the calendar timepoints).
# 2. Run `nb_0300_generate_gold_tables` after this notebook to generate gold tables.
# 
# ## NULL Unique_key Policy
# Rows with `NULL` Unique_key ARE written to silver (for audit). When gold tables are
# generated by `nb_0300_generate_gold_tables`, NULL-key rows are **excluded** from gold.
# This is an intentional design decision — NULL keys indicate grand-total/subtotal DAX rows.


# CELL ********************

import sempy.fabric as fabric
from datetime import datetime
import datetime as dt
import pandas as pd
import pyspark.sql.functions as F
from pyspark.sql.functions import lit, current_timestamp
from delta.tables import DeltaTable
import time
import logging
import concurrent.futures
import threading

logging.basicConfig(level=logging.INFO, format='%(asctime)s %(levelname)s %(message)s')
logger = logging.getLogger('nb_0220')

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

%run "./nb_0110_shared_config"

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# PARAMETERS CELL ********************

# ---------------------------------------------------------------------------
# Pipeline-injectable overrides (tag as 'parameters' for ADF/pipeline injection)
# ---------------------------------------------------------------------------
metric_workspace   = globals().get('metric_workspace', METRIC_WORKSPACE_ID)
metric_dataset     = globals().get('metric_dataset', METRIC_DATASET_ID)
target_capacity_id = globals().get('target_capacity_id', TARGET_CAPACITY_ID)

# Date range for timepoint collection (inclusive)
start_date_str = globals().get('start_date_str', DEFAULT_START_DATE_STR)
end_date_str   = globals().get('end_date_str', DEFAULT_END_DATE_STR)

# Parallelization settings
parallel_threads = globals().get('parallel_threads', 10)  # number of parallel threads for timepoint collection

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

logger.info(f"Parameters - workspace: {metric_workspace}, dataset: {metric_dataset}, capacity_id: {target_capacity_id}, start_date: {start_date_str}, end_date: {end_date_str}")

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

_raw_display = globals().get('display_data', DISPLAY_DATA)
display_data = _raw_display.strip().lower() in ('1', 'true', 'yes', 'y') if isinstance(_raw_display, str) else bool(_raw_display)

# Table targets (from config)
timepoint_calendar_table = local_table_name(SILVER_TIMEPOINTS)
silver_table_name        = local_table_name(SILVER_TP_METRICS)
count_of_connectivity_errors = 0
error_counter_lock = threading.Lock()
merge_columns = ['CapacityId', 'TimePoint', 'Unique_key', 'Operation', 'Operation_Id', 'Operation_start_time', 'Operation_end_time']
temp_store_state = create_temp_persisted_store('nb_0220')

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# -------------------------------------------------------------------------
# PREREQUISITE CHECK
# Abort early if calendar timepoints are not populated for the requested range.
# Running without them wastes time and produces no useful output.
# -------------------------------------------------------------------------
prereq_query = f"""
    SELECT COUNT(*) as n
    FROM {timepoint_calendar_table}
    WHERE TimePoint BETWEEN to_timestamp('{start_date_str}', 'dd MMMM yyyy HH:mm')
                       AND to_timestamp('{end_date_str}',   'dd MMMM yyyy HH:mm')
    AND CapacityId = '{target_capacity_id}'
"""
try:
    prereq_count = spark.sql(prereq_query).collect()[0]['n']
except Exception as ex:
    raise RuntimeError(
        f'PREREQUISITE FAILED: Cannot query {timepoint_calendar_table}. '
        f'Run nb_0110_shared_config (or run 0200 followed by 0300) first. Error: {ex}'
    )

if prereq_count == 0:
    raise RuntimeError(
        f'PREREQUISITE FAILED: No calendar timepoints found for capacity {target_capacity_id} '
        f'between {start_date_str} and {end_date_str}. '
        f'Run nb_0110_shared_config (or run 0200 followed by 0300) to populate {timepoint_calendar_table} first.'
    )

logger.info('Prerequisite OK: %d calendar timepoints found for requested range', prereq_count)

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# Log what is already in silver for this range (informational — does not skip)
try:
    existing_query = f"""
        SELECT COUNT(*) as n
        FROM {silver_table_name}
        WHERE Timepoint BETWEEN to_timestamp('{start_date_str}', 'dd MMMM yyyy HH:mm')
                            AND to_timestamp('{end_date_str}',   'dd MMMM yyyy HH:mm')
        AND CapacityId = '{target_capacity_id}'
    """
    existing_count = spark.sql(existing_query).collect()[0]['n']
    logger.info('Existing silver rows for range: %d (will final MERGE — duplicates avoided)', existing_count)
except Exception:
    logger.info('Silver table does not exist yet — will be created on first write')

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

def get_detailed_data(capacity_id, timepoint):

    capacity_id = capacity_id.upper()
    date_obj = timepoint
    date_part = f"DATE({date_obj.year}, {date_obj.month}, {date_obj.day})"
    time_part = f"TIME({date_obj.hour}, {date_obj.minute}, {date_obj.second})"
    timepoint_expr = f"{date_part} + {time_part}"

    dax_query = f"""
    DEFINE
        MPARAMETER 'TimePoint' = 
            ({timepoint_expr})

        MPARAMETER 'CapacitiesList' = 
            {{"{capacity_id}"}}

        VAR __DS0FilterTable = 
            TREATAS(
                {{"'Timepoint Background Detail'[Billing type]",
                    "'Timepoint Background Detail'[Operation Id]",
                    "'Items'[Virtualised workspace]",
                    "'Timepoint Background Detail'[Start]",
                    "'Timepoint Background Detail'[End]"}},
                'Timepoint detail page optional columns (background operations)'[DynamicColumnsTimepointBackgroundOperations Fields]
            )
        VAR __DS0FilterTable3 = 
            TREATAS({{"{capacity_id}"}}, 'Capacities'[Capacity Id])

        VAR __DS0FilterTable4 = 
            TREATAS({{{date_part}}}, 'Dates'[Date])

        VAR __DS0Core = 
            SUMMARIZECOLUMNS(
                ROLLUPADDISSUBTOTAL(
                    ROLLUPGROUP(
                        'Timepoint Background Detail'[Operation start time],
                        'Timepoint Background Detail'[Operation end time],
                        'Timepoint Background Detail'[Status],
                        'Timepoint Background Detail'[Operation],
                        'Timepoint Background Detail'[User],
                        'Items'[Workspace name],
                        'Items'[Item kind],
                        'Items'[Unique key],
                        'Timepoint Background Detail'[Billing type],
                        'Timepoint Background Detail'[Operation Id],
                        'Items'[Virtualised workspace],
                        'Timepoint Background Detail'[Start],
                        'Timepoint Background Detail'[End],
                        'Items'[Item name]
                    ), "IsGrandTotalRowTotal"
                ),
                __DS0FilterTable,
                __DS0FilterTable3,
                __DS0FilterTable4,
                "SumDuration__s_", CALCULATE(SUM('Timepoint Background Detail'[Duration (s)])),
                "SumTotal_CU__s_", CALCULATE(SUM('Timepoint Background Detail'[Total CU (s)]))
            )
    EVALUATE
        __DS0Core

    """

    #print(dax_query)
    start_time = time.time()
    timepoint_summary = fabric.evaluate_dax(
        workspace=metric_workspace,
        dataset=metric_dataset,
        dax_string=dax_query
    )
    end_time = time.time()

    if display_data:
        display(timepoint_summary)
    
    timepoint_summary.columns = ['Operation_start_time','Operation_end_time','Status','Operation','User','Workspace_name'
        ,'Item_kind','Unique_key','Billing_type','Operation_Id','Virtualised_workspace','Start','End','Item_name','IsGrandTotalRowTotal'
        ,'SumDuration_s','SumTotal_CU_s']

    row_count = len(timepoint_summary.index)
    
    if row_count == 0:
        logger.info(
            'No detail rows returned for capacity=%s timepoint=%s: %.4f seconds, %d row(s)',
            capacity_id,
            date_obj,
            end_time - start_time,
            row_count,
        )
        return
    
    timepoint_summary['TimePoint'] = pd.Timestamp(date_obj)
    timepoint_summary['CapacityId'] = capacity_id
    staged_summary = timepoint_summary.drop_duplicates(subset=merge_columns)
    duplicate_count = row_count - len(staged_summary.index)
    staged_rows = append_pandas_to_temp_store(temp_store_state, staged_summary)
    logger.info(
        'Collected and staged detail rows for capacity=%s timepoint=%s: %.4f seconds, %d row(s)',
        capacity_id,
        date_obj,
        end_time - start_time,
        staged_rows,
    )
    if duplicate_count > 0:
        logger.warning(
            'Dropped %d duplicate source row(s) before staging for capacity=%s timepoint=%s',
            duplicate_count,
            capacity_id,
            date_obj,
        )


# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

def process_timepoint_worker(cap_id, tp):
    """Worker function for parallel timepoint processing"""
    global count_of_connectivity_errors
    try:
        get_detailed_data(cap_id, tp)
    except Exception as ex:
        with error_counter_lock:
            count_of_connectivity_errors += 1
        logger.error('Error for capacity=%s timepoint=%s: %s', cap_id, tp, ex)

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

logger.info('Using temporary staged store: %s', temp_store_state['spark_path'])
try:
    # Query calendar timepoints for the requested range and iterate
    iter_query = f"""
        SELECT CapacityId, TimePoint
        FROM {timepoint_calendar_table}
        WHERE TimePoint BETWEEN to_timestamp('{start_date_str}', 'dd MMMM yyyy HH:mm')
                           AND to_timestamp('{end_date_str}',   'dd MMMM yyyy HH:mm')
        AND CapacityId = '{target_capacity_id}'
        ORDER BY CapacityId, TimePoint DESC
    """
    timepoints_df = spark.sql(iter_query)
    rows = timepoints_df.collect()
    logger.info('Processing %d timepoints...', len(rows))

    max_workers = min(parallel_threads, len(rows))  # Limit to parallel_threads concurrent threads or number of rows
    with concurrent.futures.ThreadPoolExecutor(max_workers=max_workers) as executor:
        # Submit all tasks
        futures = []
        for row in rows:
            cap_id = row['CapacityId']
            tp = to_python_datetime(row['TimePoint'])
            future = executor.submit(process_timepoint_worker, cap_id, tp)
            futures.append(future)
        
        # Wait for all tasks to complete
        concurrent.futures.wait(futures)

    if count_of_connectivity_errors > 0:
        logger.warning('Completed with %d error(s)', count_of_connectivity_errors)
    else:
        logger.info('Collection complete — no errors')

    staged_summary = load_temp_store_to_spark(temp_store_state)
    if staged_summary is None:
        logger.info('No staged detail rows found for final merge')
    else:
        synthetic_operation_id = F.concat(
            F.lit('synthetic-'),
            F.sha2(
                F.concat_ws(
                    '||',
                    F.coalesce(F.col('Operation_start_time').cast('string'), F.lit('NULL_START')),
                    F.coalesce(F.col('Operation_end_time').cast('string'), F.lit('NULL_END')),
                ),
                256,
            ),
        )
        staged_summary = (staged_summary
            .withColumn(
                'Operation_Id',
                F.when(F.col('Operation_Id').isNull(), synthetic_operation_id).otherwise(F.col('Operation_Id')),
            )
            .withColumn('insert_date', current_timestamp()))
        staged_row_count = staged_summary.count()
        deduped_summary = staged_summary.dropDuplicates(merge_columns)
        deduped_row_count = deduped_summary.count()
        duplicate_count = staged_row_count - deduped_row_count
        if duplicate_count > 0:
            logger.warning('Dropped %d duplicate staged row(s) before final merge', duplicate_count)
        merge_key = (
            "t.CapacityId = s.CapacityId "
            "AND t.TimePoint = s.TimePoint "
            "AND t.Unique_key <=> s.Unique_key "
            "AND t.Operation <=> s.Operation "
            "AND t.Operation_Id <=> s.Operation_Id "
            "AND t.Operation_start_time <=> s.Operation_start_time "
            "AND t.Operation_end_time <=> s.Operation_end_time"
        )
        max_retries = 3
        for attempt in range(1, max_retries + 1):
            try:
                if table_exists(silver_table_name):
                    dt_silver = DeltaTable.forName(spark, silver_table_name)
                    dt_silver.alias("t").merge(deduped_summary.alias("s"), merge_key)\
                        .whenMatchedUpdateAll()\
                        .whenNotMatchedInsertAll()\
                        .execute()
                else:
                    deduped_summary.write.format("delta").saveAsTable(silver_table_name)
                logger.info('Final merge completed for %d staged detail row(s)', deduped_row_count)
                break
            except Exception as ex:
                logger.warning(f'Attempt {attempt} failed with error: {ex}')
            if attempt == max_retries:
                logger.error('Max retries reached. Failed to merge data into silver table.')
                raise
            else:
                time.sleep(30)  # wait before retrying
finally:
    delete_temp_persisted_store(temp_store_state)
    logger.info('Deleted temporary staged store: %s', temp_store_state['spark_path'])

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# Log final silver row count
try:
    total = spark.sql(f'SELECT COUNT(*) as n FROM {silver_table_name}').collect()[0]['n']
    null_keys = spark.sql(f'SELECT COUNT(*) as n FROM {silver_table_name} WHERE Unique_key IS NULL').collect()[0]['n']
    logger.info('Silver %s total rows: %d | NULL Unique_key rows: %d (excluded from gold)', silver_table_name, total, null_keys)
except Exception as ex:
    logger.warning('Could not count silver rows: %s', ex)

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# Optimize silver table
maintenance_table = local_table_name(silver_table_name)
try:
    spark.sql(f'OPTIMIZE {maintenance_table}')
    spark.sql(f'VACUUM {maintenance_table} RETAIN 168 HOURS')
    spark.sql(f'ANALYZE TABLE {maintenance_table} COMPUTE STATISTICS')
    logger.info('Silver table optimized: %s', silver_table_name)
except Exception as ex:
    logger.warning('Optimize step failed (non-fatal): %s', ex)

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }


